Add new incus_network_peer resource
lxc/terraform-provider-incus pull request #157
Opened 2024-11-11 00:44 UTC by Unitiser

Hello,

This is the PR for https://github.com/lxc/terraform-provider-incus/issues/123.

2024-11-11 08:11 UTC, maveonair commented on internal/network/resource_network_peer_test.go
> +	network = "lan0"
If you do:

```hcl
network = incus_network.lan0.name
target_network: = incus_network.lan1.name
```

then you can remove the `depends_on`

2024-11-11 08:11 UTC, maveonair commented on internal/network/resource_network_peer_test.go
> +	name = "lab1-lan0"
If you do:

```hcl
network = incus_network.lan0.name
target_network: = incus_network.lan1.name
```

then you can remove the `depends_on`

2024-11-11 08:11 UTC, maveonair commented on internal/network/resource_network_peer_test.go
> +	depends_on = ["incus_network.projectA_lan0", "incus_network.projectB_lan1"]
If you do:

```hcl
network = incus_network.lan0.name
target_network: = incus_network.lan1.name
```

then you can remove the `depends_on`

2024-11-11 08:11 UTC, maveonair commented on internal/network/resource_network_peer_test.go
> +	depends_on = ["incus_network.projectA_lan0", "incus_network.projectB_lan1"]
If you do:

```hcl
network = incus_network.lan0.name
target_network: = incus_network.lan1.name
```

then you can remove the `depends_on`

2024-12-03 03:04 UTC, stgraber commented
@Unitiser any chance you can update your PR based on the comments above?
Also, we just merged https://github.com/lxc/terraform-provider-incus/pull/173 which comes with a few disabled tests that are waiting on this PR, it'd be great to add a commit which enables them.

2024-12-10 22:34 UTC, Unitiser commented
Hello, I apologize for the delay.

I made the fix you requested, hope this helps!

2024-12-16 17:40 UTC, maveonair commented
@Unitiser Please merge `origin main` or rebase from `origin main` to get the latest fixes required for CI/CD to work.

2024-12-16 18:42 UTC, maveonair requested changes
This pull request must be above the latest main branch in order to receive the required corrections for CI/CD

2024-12-17 22:01 UTC, Unitiser commented
@maveonair I resync'd the branch using the Github UI. Let me know if that's enough.

2024-12-18 01:15 UTC, stgraber commented
```
 === RUN   TestAccNetworkIntegration_attach
    resource_network_integration_test.go:99: Step 1/1 error: Error running pre-apply plan: exit status 1
        
        Error: Missing required argument
        
          on terraform_plugin_test.tf line 46, in resource "incus_network_peer" "test":
          46: resource "incus_network_peer" "test" {
        
        The argument "target_network" is required, but no definition was found.
--- FAIL: TestAccNetworkIntegration_attach (0.26s)
```

2025-01-06 20:57 UTC, Unitiser commented
I don't really use network integration. I implemented this based on the documentation. My understanding is that `network_name` is required and `network_integration` is optional. Here, it makes sense that the test fail as it is not a valid configuration.

Could you clarify the expected behaviour ?

2025-01-07 21:43 UTC, stgraber commented
For local peerings, you need `target_network`, optionally `target_project` and cannot have `target_integration`.
For remote peerings, you need `target_integration` and cannot have either `target_network` or `target_project`.

The documentation kinda mentions that in the descriptions but the required column is certainly confusing/wrong.

2025-01-30 21:26 UTC, maveonair submitted a review, later dismissed

2025-01-30 21:26 UTC, maveonair commented on docs/resources/network_peer.md
> +}
Please check the indentation and use the existing resources to look up the name, e.g., `incus_network.lan0.name`.

```suggestion
resource "incus_network" "lan0" {
  name = "lan0"
  type = "ovn"

  config = {
    # ...
  }
}

resource "incus_network" "lan1" {
  name = "lan1"
  type = "ovn"

  config = {
    # ...
  }
}

resource "incus_network_peer" "lan0_lan1"{
  name = "lab0-lan1"
  description = "A meaningful description"
  network = incus_network.lan0.name
  project = "default"
  target_network = incus_network.lan1.name
  target_project = "default"
}

resource "incus_network_peer" "lan1_lan0"{
  name = "lab1-lan0"
  description = "A meaningful description"
  network = incus_network.lan1.name
  project = "default"
  target_network = incus_network.lan0.name
  target_project = "default"
}
```

2025-02-10 23:13 UTC, stgraber approved these changes

2025-02-10 23:16 UTC, merged